version: '3.9'
services:
    open-webui:
        image: 'ghcr.io/open-webui/open-webui:main'
        restart: always
        container_name: open-webui
        devices:
          - /dev/dri:/dev/dri
        volumes:
            - './data:/app/backend/data'
        environment:
            - 'OLLAMA_BASE_URL=http://192.168.1.101:11434'
            - 'ENABLE_SIGNUP=False'
        ports:
            - '15254:8080'