x-logging-default: &logging-default
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  open-webui:
    image: "ghcr.io/open-webui/open-webui:main"
    restart: always
    container_name: open-webui
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "./data:/app/backend/data"
    environment:
      - "OLLAMA_BASE_URL=http://192.168.1.101:11434"
      - "ENABLE_SIGNUP=False"
    ports:
      - "15254:8080"
    logging: *logging-default

  open-terminal:
    image: "ghcr.io/open-webui/open-terminal:latest"
    container_name: open-terminal
    restart: always
    volumes:
      - ./ot-data:/home/user
    environment:
      - "OPEN_TERMINAL_API_KEY=changeme123"
    logging: *logging-default
