services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file: .env
    # environment:
    #   DOMAIN: "https://vault.eynsfordcq.duckdns.org"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
    #   SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - /vw-data:/data 
    ports:
      - 15260:80 