global:
  scrape_interval:     15s 

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: 'host-1'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'host-1'
  
  - job_name: 'restic-exporter'
    static_configs:
      - targets: ['restic-exporter:8001']

  - job_name: 'node_exporter_mac_mini'
    static_configs:
      - targets: ['192.168.1.101:9100']
        labels:
          instance: 'host-2'